export const countriesWithCurrency = {
  CAD: { name: "Canadian Dollar", countries: ["CA"] },
  AED: { name: "United Arab Emirates Dirham", countries: ["AE"] },
  AFN: { name: "Afghan Afghani", countries: ["AF"] },
  ALL: { name: "Albanian Lek", countries: ["AL"] },
  AMD: { name: "Armenian Dram", countries: ["AM"] },
  ANG: { name: "Netherlands Antillean Guilder", countries: ["CW", "SX"] },
  AOA: { name: "Angolan Kwanza", countries: ["AO"] },
  ARS: { name: "Argentine Peso", countries: ["AR"] },
  AUD: { name: "Australian Dollar", countries: ["AU", "NR", "KI", "TV"] },
  AWG: { name: "Aruban Florin", countries: ["AW"] },
  AZN: { name: "Azerbaijani Manat", countries: ["AZ"] },
  BAM: { name: "Bosnia-Herzegovina Convertible Mark", countries: ["BA"] },
  BBD: { name: "Barbadian Dollar", countries: ["BB"] },
  BDT: { name: "Bangladeshi Taka", countries: ["BD"] },
  BGN: { name: "Bulgarian Lev", countries: ["BG"] },
  BHD: { name: "Bahraini Dinar", countries: ["BH"] },
  BIF: { name: "Burundian Franc", countries: ["BI"] },
  BMD: { name: "Bermudian Dollar", countries: ["BM"] },
  BND: { name: "Brunei Dollar", countries: ["BN"] },
  BOB: { name: "Bolivian Boliviano", countries: ["BO"] },
  BRL: { name: "Brazilian Real", countries: ["BR"] },
  BSD: { name: "Bahamian Dollar", countries: ["BS"] },
  BTN: { name: "Bhutanese Ngultrum", countries: ["BT"] },
  BWP: { name: "Botswanan Pula", countries: ["BW"] },
  BYN: { name: "Belarusian Ruble", countries: ["BY"] },
  BZD: { name: "Belize Dollar", countries: ["BZ"] },
  CDF: { name: "Congolese Franc", countries: ["CD"] },
  CHF: { name: "Swiss Franc", countries: ["CH", "LI"] },
  CLP: { name: "Chilean Peso", countries: ["CL"] },
  CNY: { name: "Chinese Yuan", countries: ["CN"] },
  COP: { name: "Colombian Peso", countries: ["CO"] },
  CRC: { name: "Costa Rican Colón", countries: ["CR"] },
  CUP: { name: "Cuban Peso", countries: ["CU"] },
  CVE: { name: "Cape Verdean Escudo", countries: ["CV"] },
  CZK: { name: "Czech Koruna", countries: ["CZ"] },
  DJF: { name: "Djiboutian Franc", countries: ["DJ"] },
  DKK: { name: "Danish Krone", countries: ["DK", "FO", "GL"] },
  DOP: { name: "Dominican Peso", countries: ["DO"] },
  DZD: { name: "Algerian Dinar", countries: ["DZ"] },
  EGP: { name: "Egyptian Pound", countries: ["EG"] },
  ERN: { name: "Eritrean Nakfa", countries: ["ER"] },
  ETB: { name: "Ethiopian Birr", countries: ["ET"] },
  EUR: {
    name: "Euro",
    countries: [
      "AT",
      "BE",
      "CY",
      "EE",
      "FI",
      "FR",
      "DE",
      "GR",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MT",
      "MC",
      "ME",
      "NL",
      "PT",
      "SM",
      "SK",
      "SI",
      "ES",
      "VA",
    ],
  },
  FJD: { name: "Fijian Dollar", countries: ["FJ"] },
  FKP: { name: "Falkland Islands Pound", countries: ["FK"] },
  FOK: { name: "Faroese Króna", countries: ["FO"] },
  GBP: { name: "British Pound", countries: ["GB", "JE", "GG", "IM"] },
  GEL: { name: "Georgian Lari", countries: ["GE"] },
  GGP: { name: "Guernsey Pound", countries: ["GG"] },
  GHS: { name: "Ghanaian Cedi", countries: ["GH"] },
  GIP: { name: "Gibraltar Pound", countries: ["GI"] },
  GMD: { name: "Gambian Dalasi", countries: ["GM"] },
  GNF: { name: "Guinean Franc", countries: ["GN"] },
  GTQ: { name: "Guatemalan Quetzal", countries: ["GT"] },
  GYD: { name: "Guyanese Dollar", countries: ["GY"] },
  HKD: { name: "Hong Kong Dollar", countries: ["HK"] },
  HNL: { name: "Honduran Lempira", countries: ["HN"] },
  HRK: { name: "Croatian Kuna", countries: ["HR"] },
  HTG: { name: "Haitian Gourde", countries: ["HT"] },
  HUF: { name: "Hungarian Forint", countries: ["HU"] },
  IDR: { name: "Indonesian Rupiah", countries: ["ID"] },
  ILS: { name: "Israeli New Shekel", countries: ["IL"] },
  IMP: { name: "Isle of Man Pound", countries: ["IM"] },
  INR: { name: "Indian Rupee", countries: ["IN"] },
  IQD: { name: "Iraqi Dinar", countries: ["IQ"] },
  IRR: { name: "Iranian Rial", countries: ["IR"] },
  ISK: { name: "Icelandic Króna", countries: ["IS"] },
  JEP: { name: "Jersey Pound", countries: ["JE"] },
  JMD: { name: "Jamaican Dollar", countries: ["JM"] },
  JOD: { name: "Jordanian Dinar", countries: ["JO"] },
  JPY: { name: "Japanese Yen", countries: ["JP"] },
  KES: { name: "Kenyan Shilling", countries: ["KE"] },
  KGS: { name: "Kyrgyzstani Som", countries: ["KG"] },
  KHR: { name: "Cambodian Riel", countries: ["KH"] },
  KID: { name: "Kiribati Dollar", countries: ["KI"] },
  KMF: { name: "Comorian Franc", countries: ["KM"] },
  KRW: { name: "South Korean Won", countries: ["KR"] },
  KWD: { name: "Kuwaiti Dinar", countries: ["KW"] },
  KYD: { name: "Cayman Islands Dollar", countries: ["KY"] },
  KZT: { name: "Kazakhstani Tenge", countries: ["KZ"] },
  LAK: { name: "Lao Kip", countries: ["LA"] },
  LBP: { name: "Lebanese Pound", countries: ["LB"] },
  LKR: { name: "Sri Lankan Rupee", countries: ["LK"] },
  LRD: { name: "Liberian Dollar", countries: ["LR"] },
  LSL: { name: "Lesotho Loti", countries: ["LS"] },
  LYD: { name: "Libyan Dinar", countries: ["LY"] },
  MAD: { name: "Moroccan Dirham", countries: ["MA"] },
  MDL: { name: "Moldovan Leu", countries: ["MD"] },
  MGA: { name: "Malagasy Ariary", countries: ["MG"] },
  MKD: { name: "Macedonian Denar", countries: ["MK"] },
  MMK: { name: "Myanmar Kyat", countries: ["MM"] },
  MNT: { name: "Mongolian Tögrög", countries: ["MN"] },
  MOP: { name: "Macanese Pataca", countries: ["MO"] },
  MRU: { name: "Mauritanian Ouguiya", countries: ["MR"] },
  MUR: { name: "Mauritian Rupee", countries: ["MU"] },
  MVR: { name: "Maldivian Rufiyaa", countries: ["MV"] },
  MWK: { name: "Malawian Kwacha", countries: ["MW"] },
  MXN: { name: "Mexican Peso", countries: ["MX"] },
  MYR: { name: "Malaysian Ringgit", countries: ["MY"] },
  MZN: { name: "Mozambican Metical", countries: ["MZ"] },
  NAD: { name: "Namibian Dollar", countries: ["NA"] },
  NGN: { name: "Nigerian Naira", countries: ["NG"] },
  NIO: { name: "Nicaraguan Córdoba", countries: ["NI"] },
  NOK: { name: "Norwegian Krone", countries: ["NO", "SJ"] },
  NPR: { name: "Nepalese Rupee", countries: ["NP"] },
  NZD: {
    name: "New Zealand Dollar",
    countries: ["NZ", "CK", "NU", "PN", "TK"],
  },
  OMR: { name: "Omani Rial", countries: ["OM"] },
  PAB: { name: "Panamanian Balboa", countries: ["PA"] },
  PEN: { name: "Peruvian Sol", countries: ["PE"] },
  PGK: { name: "Papua New Guinean Kina", countries: ["PG"] },
  PHP: { name: "Philippine Peso", countries: ["PH"] },
  PKR: { name: "Pakistani Rupee", countries: ["PK"] },
  PLN: { name: "Polish Zloty", countries: ["PL"] },
  PYG: { name: "Paraguayan Guarani", countries: ["PY"] },
  QAR: { name: "Qatari Rial", countries: ["QA"] },
  RON: { name: "Romanian Leu", countries: ["RO"] },
  RSD: { name: "Serbian Dinar", countries: ["RS"] },
  RUB: { name: "Russian Ruble", countries: ["RU"] },
  RWF: { name: "Rwandan Franc", countries: ["RW"] },
  SAR: { name: "Saudi Riyal", countries: ["SA"] },
  SBD: { name: "Solomon Islands Dollar", countries: ["SB"] },
  SCR: { name: "Seychellois Rupee", countries: ["SC"] },
  SDG: { name: "Sudanese Pound", countries: ["SD"] },
  SEK: { name: "Swedish Krona", countries: ["SE"] },
  SGD: { name: "Singapore Dollar", countries: ["SG"] },
  SHP: { name: "Saint Helena Pound", countries: ["SH"] },
  SLE: { name: "Sierra Leonean Leone", countries: ["SL"] },
  SLL: { name: "Sierra Leonean Leone", countries: ["SL"] },
  SOS: { name: "Somali Shilling", countries: ["SO"] },
  SRD: { name: "Surinamese Dollar", countries: ["SR"] },
  SSP: { name: "South Sudanese Pound", countries: ["SS"] },
  STN: { name: "São Tomé and Príncipe Dobra", countries: ["ST"] },
  SYP: { name: "Syrian Pound", countries: ["SY"] },
  SZL: { name: "Swazi Lilangeni", countries: ["SZ"] },
  THB: { name: "Thai Baht", countries: ["TH"] },
  TJS: { name: "Tajikistani Somoni", countries: ["TJ"] },
  TMT: { name: "Turkmenistani Manat", countries: ["TM"] },
  TND: { name: "Tunisian Dinar", countries: ["TN"] },
  TOP: { name: "Tongan Paʻanga", countries: ["TO"] },
  TRY: { name: "Turkish Lira", countries: ["TR"] },
  TTD: { name: "Trinidad and Tobago Dollar", countries: ["TT"] },
  TVD: { name: "Tuvaluan Dollar", countries: ["TV"] },
  TWD: { name: "New Taiwan Dollar", countries: ["TW"] },
  TZS: { name: "Tanzanian Shilling", countries: ["TZ"] },
  UAH: { name: "Ukrainian Hryvnia", countries: ["UA"] },
  UGX: { name: "Ugandan Shilling", countries: ["UG"] },
  USD: {
    name: "US Dollar",
    countries: [
      "US",
      "AS",
      "BQ",
      "SX",
      "IO",
      "EC",
      "SV",
      "GU",
      "HT",
      "MH",
      "FM",
      "MP",
      "PW",
      "PA",
      "PR",
      "TL",
      "TC",
      "UM",
      "VG",
      "VI",
    ],
  },
  UYU: { name: "Uruguayan Peso", countries: ["UY"] },
  UZS: { name: "Uzbekistani Som", countries: ["UZ"] },
  VES: { name: "Venezuelan Bolívar", countries: ["VE"] },
  VND: { name: "Vietnamese Dong", countries: ["VN"] },
  VUV: { name: "Vanuatu Vatu", countries: ["VU"] },
  WST: { name: "Samoan Tala", countries: ["WS"] },
  XAF: {
    name: "Central African CFA Franc",
    countries: ["CM", "CF", "TD", "CG", "GQ", "GA"],
  },
  XCD: {
    name: "East Caribbean Dollar",
    countries: ["AI", "AG", "DM", "GD", "KN", "LC", "VC"],
  },
  XDR: { name: "Special Drawing Rights", countries: ["IMF"] },
  XOF: {
    name: "West African CFA Franc",
    countries: ["BJ", "BF", "GW", "CI", "ML", "NE", "SN", "TG"],
  },
  XPF: { name: "CFP Franc", countries: ["PF", "NC", "WF"] },
  YER: { name: "Yemeni Rial", countries: ["YE"] },
  ZAR: { name: "South African Rand", countries: ["ZA"] },
  ZMW: { name: "Zambian Kwacha", countries: ["ZM"] },
  ZWL: { name: "Zimbabwean Dollar", countries: ["ZW"] },
};

export const convertCurrency = (
  amount: number,
  fromCurrency: string,
  toCurrency: string,
  exchangeRates: { [key: string]: number }
): number => {
  if (fromCurrency === toCurrency) return amount;
  const baseAmount = amount / exchangeRates[fromCurrency];
  return baseAmount * exchangeRates[toCurrency];
};

export const formatCurrency = (amount: number, currency: string): string => {
  return new Intl.NumberFormat("en-US", { style: "currency", currency }).format(
    amount
  );
};

export const getCurrencyByCountry = (country: string): string => {
  for (const [currency, { countries }] of Object.entries(
    countriesWithCurrency
  )) {
    if (countries.includes(country)) {
      return currency;
    }
  }
  return "CAD";
};
